server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: text/plain applcation/x-javascript application/javascript text/css text/xml application/xml application/xml+rss text/javascript application/x-httpd-php
spring:
  application:
    name: Leryn Homepage
  datasource:
    driver-class-name: ${DB_JDBC_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    hikari:
      pool-name: DateHikariCP
      maximum-pool-size: 50
      max-lifetime: 18000
      idle-timeout: 18000
      auto-commit: true
      minimum-idle: 5
      connection-timeout: 3000
      connection-test-query: select 1 from dual
  jackson:
    date-format: yyyy-MM-dd HH:mm:SS
    time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB