/*
 * This file is generated by jOOQ.
 */
package io.github.leryn.homepage.data.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 地址导航
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sitemap implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        name;
    private String        title;
    private String        description;
    private String        url;
    private String        logo;
    private Boolean       deleted;
    private LocalDateTime createTime;
    private LocalDateTime modifiedTime;

    public Sitemap() {}

    public Sitemap(Sitemap value) {
        this.id = value.id;
        this.name = value.name;
        this.title = value.title;
        this.description = value.description;
        this.url = value.url;
        this.logo = value.logo;
        this.deleted = value.deleted;
        this.createTime = value.createTime;
        this.modifiedTime = value.modifiedTime;
    }

    public Sitemap(
        Integer       id,
        String        name,
        String        title,
        String        description,
        String        url,
        String        logo,
        Boolean       deleted,
        LocalDateTime createTime,
        LocalDateTime modifiedTime
    ) {
        this.id = id;
        this.name = name;
        this.title = title;
        this.description = description;
        this.url = url;
        this.logo = logo;
        this.deleted = deleted;
        this.createTime = createTime;
        this.modifiedTime = modifiedTime;
    }

    /**
     * Getter for <code>homepage.sitemap.id</code>. 主键
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>homepage.sitemap.id</code>. 主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>homepage.sitemap.name</code>. 名称(缩写)
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>homepage.sitemap.name</code>. 名称(缩写)
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>homepage.sitemap.title</code>. 标题
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>homepage.sitemap.title</code>. 标题
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>homepage.sitemap.description</code>. 描述
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>homepage.sitemap.description</code>. 描述
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>homepage.sitemap.url</code>. 地址URL
     */
    public String getUrl() {
        return this.url;
    }

    /**
     * Setter for <code>homepage.sitemap.url</code>. 地址URL
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * Getter for <code>homepage.sitemap.logo</code>. 图标URL
     */
    public String getLogo() {
        return this.logo;
    }

    /**
     * Setter for <code>homepage.sitemap.logo</code>. 图标URL
     */
    public void setLogo(String logo) {
        this.logo = logo;
    }

    /**
     * Getter for <code>homepage.sitemap.deleted</code>. 是否删除:1-未删除,0-删除
     */
    public Boolean getDeleted() {
        return this.deleted;
    }

    /**
     * Setter for <code>homepage.sitemap.deleted</code>. 是否删除:1-未删除,0-删除
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * Getter for <code>homepage.sitemap.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>homepage.sitemap.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>homepage.sitemap.modified_time</code>. 修改时间
     */
    public LocalDateTime getModifiedTime() {
        return this.modifiedTime;
    }

    /**
     * Setter for <code>homepage.sitemap.modified_time</code>. 修改时间
     */
    public void setModifiedTime(LocalDateTime modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Sitemap (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(title);
        sb.append(", ").append(description);
        sb.append(", ").append(url);
        sb.append(", ").append(logo);
        sb.append(", ").append(deleted);
        sb.append(", ").append(createTime);
        sb.append(", ").append(modifiedTime);

        sb.append(")");
        return sb.toString();
    }
}
