/*
 * This file is generated by jOOQ.
 */
package io.github.leryn.homepage.data.tables.records;


import io.github.leryn.homepage.data.tables.Sitemap;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 地址导航
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SitemapRecord extends UpdatableRecordImpl<SitemapRecord> implements Record9<Integer, String, String, String, String, String, Boolean, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>homepage.sitemap.id</code>. 主键
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>homepage.sitemap.id</code>. 主键
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>homepage.sitemap.name</code>. 名称(缩写)
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>homepage.sitemap.name</code>. 名称(缩写)
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>homepage.sitemap.title</code>. 标题
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>homepage.sitemap.title</code>. 标题
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>homepage.sitemap.description</code>. 描述
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>homepage.sitemap.description</code>. 描述
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>homepage.sitemap.url</code>. 地址URL
     */
    public void setUrl(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>homepage.sitemap.url</code>. 地址URL
     */
    public String getUrl() {
        return (String) get(4);
    }

    /**
     * Setter for <code>homepage.sitemap.logo</code>. 图标URL
     */
    public void setLogo(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>homepage.sitemap.logo</code>. 图标URL
     */
    public String getLogo() {
        return (String) get(5);
    }

    /**
     * Setter for <code>homepage.sitemap.deleted</code>. 是否删除:1-未删除,0-删除
     */
    public void setDeleted(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>homepage.sitemap.deleted</code>. 是否删除:1-未删除,0-删除
     */
    public Boolean getDeleted() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>homepage.sitemap.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>homepage.sitemap.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>homepage.sitemap.modified_time</code>. 修改时间
     */
    public void setModifiedTime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>homepage.sitemap.modified_time</code>. 修改时间
     */
    public LocalDateTime getModifiedTime() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, String, String, String, String, String, Boolean, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, String, String, String, String, String, Boolean, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Sitemap.SITEMAP.ID;
    }

    @Override
    public Field<String> field2() {
        return Sitemap.SITEMAP.NAME;
    }

    @Override
    public Field<String> field3() {
        return Sitemap.SITEMAP.TITLE;
    }

    @Override
    public Field<String> field4() {
        return Sitemap.SITEMAP.DESCRIPTION;
    }

    @Override
    public Field<String> field5() {
        return Sitemap.SITEMAP.URL;
    }

    @Override
    public Field<String> field6() {
        return Sitemap.SITEMAP.LOGO;
    }

    @Override
    public Field<Boolean> field7() {
        return Sitemap.SITEMAP.DELETED;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Sitemap.SITEMAP.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return Sitemap.SITEMAP.MODIFIED_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getTitle();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public String component5() {
        return getUrl();
    }

    @Override
    public String component6() {
        return getLogo();
    }

    @Override
    public Boolean component7() {
        return getDeleted();
    }

    @Override
    public LocalDateTime component8() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component9() {
        return getModifiedTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getTitle();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public String value5() {
        return getUrl();
    }

    @Override
    public String value6() {
        return getLogo();
    }

    @Override
    public Boolean value7() {
        return getDeleted();
    }

    @Override
    public LocalDateTime value8() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value9() {
        return getModifiedTime();
    }

    @Override
    public SitemapRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SitemapRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public SitemapRecord value3(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public SitemapRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public SitemapRecord value5(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public SitemapRecord value6(String value) {
        setLogo(value);
        return this;
    }

    @Override
    public SitemapRecord value7(Boolean value) {
        setDeleted(value);
        return this;
    }

    @Override
    public SitemapRecord value8(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public SitemapRecord value9(LocalDateTime value) {
        setModifiedTime(value);
        return this;
    }

    @Override
    public SitemapRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, Boolean value7, LocalDateTime value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SitemapRecord
     */
    public SitemapRecord() {
        super(Sitemap.SITEMAP);
    }

    /**
     * Create a detached, initialised SitemapRecord
     */
    public SitemapRecord(Integer id, String name, String title, String description, String url, String logo, Boolean deleted, LocalDateTime createTime, LocalDateTime modifiedTime) {
        super(Sitemap.SITEMAP);

        setId(id);
        setName(name);
        setTitle(title);
        setDescription(description);
        setUrl(url);
        setLogo(logo);
        setDeleted(deleted);
        setCreateTime(createTime);
        setModifiedTime(modifiedTime);
    }
}
