/*
 * This file is generated by jOOQ.
 */
package io.github.leryn.homepage.data;


import io.github.leryn.homepage.data.tables.Sitemap;


/**
 * Convenience access to all tables in homepage.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 地址导航
     */
    public static final Sitemap SITEMAP = Sitemap.SITEMAP;
}
